version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - database_backend
    ports:
      - 8080:8080
    volumes:
      - ./:/srv/backend
    environment:
      JDBC_URL: "jdbc:postgresql://database_backend:5432/backend"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_MIGRATIONS_LOCATION: filesystem:resources/db/migrations
  database_backend:
    image: postgres
    restart: always
    volumes:
      - backend_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
volumes:
  backend_data: