micronaut:
  application:
    name: demo
datasources:
  default:
    url: ${JDBC_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
